version: '3.2'

services:
  nginx:
    container_name: app-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    container_name: app-php
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgresql
      - redis

  postgresql:
    container_name: app-postgresql
    image: postgres:latest
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"

  redis:
    container_name: app-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data

volumes:
  database:

networks:
  default:
    driver: bridge
