version: '3.2'

services:
  nginx:
    container_name: app-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    container_name: app-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
    depends_on:
      - mysql

  mysql:
    container_name: app-mysql
    image: mysql:8.0
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootSecret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
    ports:
      - "3316:3306"

volumes:
  database:

networks:
  default:
    driver: bridge
